### PR TITLE
fix admonition

### LINKED ISSUE #28: Admonition icons not rendering
The icons are not rendered.

See AsciiDoc [documentation](http://asciidoctor.org/docs/user-manual/#admonition). also amend `feature.adoc`

### PR DESCRIPTION
**Pull request by ghost**
I fix #28 

My environment activate admonition.

### CODE REVIEW

**Comment by madmas** [comment]
Hi @asdfg0280 , thanks a lot for the PR!
I wanted to try it befire merge, so I pulled your branch and did this:

bildschirmfoto 2018-07-23 um 16 12 39

(did and `npm run build` and `npm start`)
The CSS classes are applied nicely, but the icon are not shown - any idea why taht might be the case?

**Comment by ghost** [comment]
uh?
My environment is correct to render.
image
I use Dockerfile. If you can use it, try it.

**Comment by ghost** [comment]
My friend says your computer did not install emoji font,did it?
So,plz check it.

and,run dockerfile.(Maybe,Docker is correct render.)

**Comment by madmas** [comment]
Yes, I agree that obviously, the font is missing or not applied :) 
I've tried both a local build and the dockerized version. The same effect,  the font is missing.

I can see that `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css`is loaded in the network tab of my browser debug console and also `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0`
But it's not used then. What OS / browser do you use?

**Comment by ghost** [comment]
My computer is win10 / google chrome.
If you want to try some environment, I try it.

**Comment by madmas** [comment]
Okay, I sorted it out, there was a issue in my environment:

bildschirmfoto 2018-07-25 um 09 25 35

Now it looks good, thank you :)

**Comment by ghost** [comment]
Oh! That's nice!
By the way, Will I rewrite readme.adoc ?
Cuz' we can render admonition correctly.

**Pull request merged**
