### PR TITLE
Add feature description for the line-through/strike-through text formatting

### PR DESCRIPTION
**Pull request by ursjoss**
This PR adds the strike-through/line-through description from pull request #33 to the feature documentation.

### CODE REVIEW

**Review by PReimers — APPROVED** [review]

**Comment by PReimers** [comment]
Tanks 👍

**Comment by madmas** [comment]
@ursjoss of course. 🙄 I totally missed that even though that was my starting point .. thanks a lot :)

**Comment by ursjoss** [comment]
Sure. And I somehow missed turning this into a github issue initially...

**Comment by PReimers** [comment]
Is it required to open an issue if it‘s just a small improvement?

I would say it needs an issue, when it can’t be fixed directly.

**Comment by ursjoss** [comment]
Nearly fully agree. When I went through the features document though, I identified 15+ issues, some of them minor, some of them unknown in terms of needed effort.

In this situation I consider it better to document the issues identified. I was referring to that, as I did not do that for the strike-through topic...

**Pull request merged**
