### PR TITLE
Change/suggest external and icon

### PR DESCRIPTION
**Pull request by ghost**
#30 

I change suggesting term.

### CODE REVIEW

**Comment by madmas** [comment]
Hi, thanks a lot for the PR, great work!
Just one thing: can you include screenshots and steps to reproduce what your changes do? :) That makes it a lot easier to review the changes :)

**Comment by ghost** [comment]
sry.
for example, typing youtube , like this.
image

externals supports to add tags.

**Comment by madmas** [comment]
thanks for the screenshot. it does not show what I've expected after our discussion in #30, though ;-)

but one thing first: this PR also contains changes that do not belong in here as described in https://github.com/hackergarten/hackadoc/pull/46#issuecomment-407664079 - can you update this as well?

**Comment by ghost** [comment]
Sry my poor git's skill.I try to contribute OSS first time.
I try to clean branch.Please wait for cleaning branch and commit.

**Comment by ghost** [comment]
I'm sry. I try to clean up branch.

**Pull request closed without merging**
