### PR TITLE
Minimal implementation of title extraction

### PR DESCRIPTION
**Pull request by ursjoss**

### CODE REVIEW

**Comment by PReimers** [comment]
This should relate to #2 😉

**Comment by ursjoss** [comment]
Exactly. And much of the credit to @l33tname, who was pairing with me

**Comment by PReimers** [comment]
@ursjoss
Why did you close the PR?

**Comment by ursjoss** [comment]
I am issueing a new one soon :-)

**Comment by ursjoss** [comment]
Closed in favor of PR #12

**Pull request closed without merging**
